global class ContactDomain {
    global class UserInfo {
        //public String SellerId;
        public String UserId;
        public String DistributorId;
        public String DistributorName;
        public String BranchId;
        public String UserName;
        public String CurrentDate;
        public String Timezone;
        public String Address1;
        public String MobileNo;
        public String UserType;
        public String LoginId;
    }
    
    global class RetailerInfo {
        public String SellerId;
        public String RetailerCode;
        public String RetailerName;
        public String Address1;
        public String BeatId;
        public String ChannelId;
        public Decimal Latitude;
        public Decimal Longitude;
        public String SubChannelId;
        
    }
}